services:
  postgres:
    image: postgres:15-alpine
    container_name: rv-park-postgres
    environment:
      POSTGRES_DB: reservation_system
      POSTGRES_USER: rvpark
      POSTGRES_PASSWORD: rvpark123
      PGUSER: rvpark
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rvpark -d reservation_system"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rv-park-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rvpark.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  app:
    build: .
    container_name: rv-park-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/reservation_system
      - SPRING_DATASOURCE_USERNAME=rvpark
      - SPRING_DATASOURCE_PASSWORD=rvpark123
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - PARK_EMAIL=${PARK_EMAIL:-noreply@alpineridgervpark.com}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: 